(cl:defpackage planning2-msg
  (:use )
  (:export
   "<GOTOTASKFEEDBACK>"
   "GOTOTASKFEEDBACK"
   "<GOTOTASKRESULT>"
   "GOTOTASKRESULT"
   "<GOTOTASKACTIONFEEDBACK>"
   "GOTOTASKACTIONFEEDBACK"
   "<GOTOTASKACTIONRESULT>"
   "GOTOTASKACTIONRESULT"
   "<GOTOTASKACTIONGOAL>"
   "GOTOTASKACTIONGOAL"
   "<GOTOTASKGOAL>"
   "GOTOTASKGOAL"
   "<GOTOTASKACTION>"
   "GOTOTASKACTION"
  ))

