; Auto-generated. Do not edit!


(cl:in-package planning2-msg)


;//! \htmlinclude GoToTaskFeedback.msg.html

(cl:defclass <GoToTaskFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass GoToTaskFeedback (<GoToTaskFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GoToTaskFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GoToTaskFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name planning2-msg:<GoToTaskFeedback> is deprecated: use planning2-msg:GoToTaskFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GoToTaskFeedback>) ostream)
  "Serializes a message object of type '<GoToTaskFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GoToTaskFeedback>) istream)
  "Deserializes a message object of type '<GoToTaskFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GoToTaskFeedback>)))
  "Returns string type for a message object of type '<GoToTaskFeedback>"
  "planning2/GoToTaskFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GoToTaskFeedback)))
  "Returns string type for a message object of type 'GoToTaskFeedback"
  "planning2/GoToTaskFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GoToTaskFeedback>)))
  "Returns md5sum for a message object of type '<GoToTaskFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GoToTaskFeedback)))
  "Returns md5sum for a message object of type 'GoToTaskFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GoToTaskFeedback>)))
  "Returns full string definition for message of type '<GoToTaskFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GoToTaskFeedback)))
  "Returns full string definition for message of type 'GoToTaskFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GoToTaskFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GoToTaskFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'GoToTaskFeedback
))
