// Generated by gencpp from file planning2/GoToTaskFeedback.msg
// DO NOT EDIT!


#ifndef PLANNING2_MESSAGE_GOTOTASKFEEDBACK_H
#define PLANNING2_MESSAGE_GOTOTASKFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace planning2
{
template <class ContainerAllocator>
struct GoToTaskFeedback_
{
  typedef GoToTaskFeedback_<ContainerAllocator> Type;

  GoToTaskFeedback_()
    {
    }
  GoToTaskFeedback_(const ContainerAllocator& _alloc)
    {
    }






  typedef boost::shared_ptr< ::planning2::GoToTaskFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planning2::GoToTaskFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct GoToTaskFeedback_

typedef ::planning2::GoToTaskFeedback_<std::allocator<void> > GoToTaskFeedback;

typedef boost::shared_ptr< ::planning2::GoToTaskFeedback > GoToTaskFeedbackPtr;
typedef boost::shared_ptr< ::planning2::GoToTaskFeedback const> GoToTaskFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planning2::GoToTaskFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planning2::GoToTaskFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace planning2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'planning2': ['/opt/codigo/ros/simulator/catkin_ws/src/planning2/devel/share/planning2/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::planning2::GoToTaskFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planning2::GoToTaskFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planning2::GoToTaskFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planning2::GoToTaskFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planning2::GoToTaskFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planning2::GoToTaskFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planning2::GoToTaskFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::planning2::GoToTaskFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::planning2::GoToTaskFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planning2/GoToTaskFeedback";
  }

  static const char* value(const ::planning2::GoToTaskFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planning2::GoToTaskFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#feedback\n\
";
  }

  static const char* value(const ::planning2::GoToTaskFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planning2::GoToTaskFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct GoToTaskFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planning2::GoToTaskFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::planning2::GoToTaskFeedback_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // PLANNING2_MESSAGE_GOTOTASKFEEDBACK_H
